### ISSUE TITLE
Encoding issue with chinese

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-python#24]
I just upgrade the API client and get this error message when search in Chinese Characters:

```
Traceback (most recent call last):
File "/Users/sainteye/.virtualenvs/foodblogs/lib/python2.7/site-packages/algoliasearch/index.py", line 386, in search
params = {'params': urlencode(urlify(args))}
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1347, in urlencode
v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

@dethi any chance you can help?

**Comment by redox** [comment]
Downgrading to 1.5.9 fixes the issue.

**Comment by dethi** [comment]
I will take a look today!
