### ISSUE TITLE
requests expect timeout as a float instead of a tuple

### ISSUE THREAD

**Issue by iurisilvio** [algolia/algoliasearch-client-python#36]
```
Traceback (most recent call last):
  File "static_script_algolia_index.py", line 121, in <module>
    days=options.days)
  File "static_script_algolia_index.py", line 79, in main
    index.clear_index()
  File "/usr/local/lib/python2.7/dist-packages/algoliasearch/index.py", line 588, in clear_index
    return self._perform_request(self.write_hosts, '/clear', 'POST')
  File "/usr/local/lib/python2.7/dist-packages/algoliasearch/index.py", line 820, in _perform_request
    params=params, body=body, is_search=is_search)
  File "/usr/local/lib/python2.7/dist-packages/algoliasearch/client.py", line 499, in _perform_request
    params=params, data=body, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 316, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 116, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 147, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was (1, 30), but it must be an int or float.
```

**Comment by Nagriar** [comment]
Hi @iurisilvio,

Could you upgrade your version of the requests library? The API Client only works with a version >= 2.4.1.

Best regards,

**Comment by iurisilvio** [comment]
Yes, I fixed it upgrading requests lib.

Thanks!
