### ISSUE TITLE
cannot install algoliasearch on python3.4 ubuntu 14.04

### ISSUE THREAD

**Issue by gregorth** [algolia/algoliasearch-client-python#37]
basically on python3.4 installing pip dependencies from custom requirements.txt crash when it starts to install algolia, here is the trace:

```


Collecting Pillow==3.0.0 (from -r /home/iplay/app/requirements.txt (line 14))
  Using cached Pillow-3.0.0.tar.gz
Collecting pypandoc==1.1.2 (from -r /home/iplay/app/requirements.txt (line 15))
  Using cached pypandoc-1.1.2.zip
Collecting algoliasearch==1.7.1 (from -r /home/iplay/app/requirements.txt (line 16))
  Using cached algoliasearch-1.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-4mlicdah/algoliasearch/setup.py", line 17, in <module>
        import pypandoc
    ImportError: No module named 'pypandoc'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4mlicdah/algoliasearch/setup.py", line 21, in <module>
        README = readme.read()
      File "/home/iplay/app/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 23832: ordinal not in range(128)
    
    ----------------------------------------

:stderr: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4mlicdah/algoliasearch
```
possible way to avoid above crash is to install pypandoc before installing algolia, however it isn't case when we do automating deploy

**Comment by dethi** [comment]
Well, the requirements.txt in the repository is for the developer. Pypandoc is used only by the setup.py

Maybe I can move these dependencies in another file, like requirements_dev.txt
