### ISSUE TITLE
ImportError: No module named typing

### ISSUE THREAD

**Issue by rodrigoreis22** [algolia/algoliasearch-client-python#485]
- Algolia Client Version: 2.2.0
- Language Version: Python 2.7.16
- macOS Catalina 10.15.4

### Description

I install my requirements using a `requirements.txt` file that looks like this:

```
requests
pymongo==3.6.1
python-dateutil
algoliasearch>=2.0,<3.0
xmltodict
pytz
```

Install dependencies script:
```
rm -rf vendored/
pip install -t vendored/ -r requirements.txt
```

Then when I try to run my scripts I get an error like this:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/rodrigoreis/Documents/arena-etl/tests/fsau_afl_importer_test.py", line 1, in <module>
    from lib.foxsportsau.afl_importer import AFLImporter
  File "/Users/rodrigoreis/Documents/arena-etl/lib/foxsportsau/afl_importer.py", line 5, in <module>
    import lib.model.persistence as persistence
  File "/Users/rodrigoreis/Documents/arena-etl/lib/model/persistence.py", line 2, in <module>
    import lib.db.algolia as algolia
  File "/Users/rodrigoreis/Documents/arena-etl/lib/db/algolia.py", line 1, in <module>
    from algoliasearch.search_client import SearchClient
  File "/Users/rodrigoreis/Documents/arena-etl/lib/vendored/algoliasearch/search_client.py", line 8, in <module>
    from typing import Optional, Union, List, Iterator
ImportError: No module named typing
```

I've already tried algolia client versions 2.0.1 and 2.0.2 as well.

### Steps To Reproduce
1. With python 2.7.16 install the algolia client
2. import the algolia client
3. run (the error will be displayed)

**Comment by nunomaduro** [comment]
Weird, it seems required here: https://github.com/algolia/algoliasearch-client-python/blob/1b487732c8f207a010340096eb1f6138bea727fa/requirements.txt#L11.

**Comment by nunomaduro** [comment]
Make sure you installed the requirements correctly, if they seem correctly installed to you get back to me. Thanks!
