### ISSUE TITLE
Algoliasearch client cannot be installed via Pipenv

### ISSUE THREAD

**Issue by Anto59290** [algolia/algoliasearch-client-python#499]
- Algolia Client Version: 2.3.0
- Language Version: Python 3.7.7

### Description
Pipenv is a packaging tool that allows to install python package and to handle .lock files. See [this page for more details](https://pipenv-fork.readthedocs.io/en/latest/basics.html)

When trying to install Algolia search client with Pipenv in a clean environment I get the following error:

```bash
antonin@antonin:~/imake/test$ pipenv install algoliasearch
Installing algoliasearch…
Adding algoliasearch to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 803, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 753, in resolve_packages
    requirements_dir=requirements_dir,
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 736, in resolve
    req_dir=requirements_dir
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1386, in resolve_deps
    req_dir=req_dir,
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1095, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 847, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 288, in cleanup_pyspecs
    for op_and_version_type, versions in _group_by_op(tuple(specs)):
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in _group_by_op
    specs = [_get_specs(x) for x in list(specs)]
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in <listcomp>
    specs = [_get_specs(x) for x in list(specs)]
  File "/home/antonin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 187, in _get_specs
    for spec in set(specset):
TypeError: 'LegacySpecifier' object is not iterable
``` 
What is expected is that it should install the search client without any errors. 

A coworker of mine (@Afnarel) pointed me in the correct direction by saying that the `setup.cfg` file had [a weird syntax](https://github.com/algolia/algoliasearch-client-python/blob/master/setup.cfg#L39). I cloned the repo and made a minor modification on the `python_requires` line ([see the change](https://github.com/Anto59290/algoliasearch-client-python/blob/master/setup.cfg#L39)). By using my repo the package can now be installed with Pipenv without issues.

I know this is probably not an important issue (as the library can still be used/installed via pip) but I believe the fix is pretty simple.

I was also surprised that other tools used for packaging did not raised an error before that and that the error is only visible when using Pipenv to install the library.

As far as I can tell I believe 77a9fd051de255cf930270a29a56560d48b561a0 [introduced the issue](https://github.com/algolia/algoliasearch-client-python/commit/77a9fd051de255cf930270a29a56560d48b561a0#diff-380c6a8ebbbce17d55d50ef17d3cf906R37).

Thanks for your time and have a good day.

### Steps To Reproduce
With Pipenv set up (on Python 3.7.7) run `pipenv install algoliasearch` . The installation will fail.

**Comment by nunomaduro** [comment]
Thanks for reporting this, I am on it...

**Comment by nunomaduro** [comment]
This issue has been fixed.

**Comment by Anto59290** [comment]
Thanks @nunomaduro Have a good day :)
